name = "GeoStatsTransforms"
uuid = "725d9659-360f-4996-9c94-5f19c7e4a8a6"
authors = ["Júlio Hoffimann <julio.hoffimann@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
